.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. grailum_qt test_grailum_qt
clean: FORCE
	$(MAKE) -C .. grailum_qt_clean test_grailum_qt_clean
check: FORCE
	$(MAKE) -C .. test_grailum_qt_check
grailum-qt grailum-qt.exe: FORCE
	 $(MAKE) -C .. grailum_qt
